/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts}",
    "./public/index.html",
    "./public/src/**/*.{js,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#533d00",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#251a00",
        "on-secondary-fixed": "#022016",
        "outline": "#999080",
        "on-tertiary-container": "#42413c",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#4d4639",
        "tertiary-fixed": "#e6e2db",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#5a4302",
        "inverse-primary": "#745b1b",
        "on-tertiary-fixed-variant": "#484742",
        "secondary-container": "#304d40",
        "error": "#ffb4ab",
        "on-background": "#e5e2e1",
        "on-secondary-fixed-variant": "#304d40",
        "on-secondary-container": "#9cbcad",
        "secondary": "#adcebe",
        "background": "#131313",
        "primary-fixed": "#ffdf9b",
        "on-secondary": "#19362b",
        "error-container": "#93000a",
        "on-tertiary": "#31302c",
        "surface-tint": "#e4c278",
        "on-surface-variant": "#d0c5b4",
        "primary": "#e6c479",
        "inverse-on-surface": "#313030",
        "tertiary-container": "#b0ada6",
        "primary-fixed-dim": "#e4c278",
        "tertiary-fixed-dim": "#c9c6c0",
        "primary-container": "#c9a961",
        "surface-bright": "#3a3939",
        "tertiary": "#cbc8c1",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "on-primary": "#3f2e00",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#adcebe",
        "inverse-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353534",
        "on-tertiary-fixed": "#1c1c18",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#c9ead9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-xs": "4px",
        "margin-mobile": "20px",
        "unit": "4px",
        "container-max": "1440px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "stack-xl": "96px",
        "stack-lg": "48px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "display-xl": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["80px", {"lineHeight": "88px", "letterSpacing": "-0.04em", "fontWeight": "200"}],
        "display-xl-mobile": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "300"}],
        "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "300"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "label-caps": ["11px", {"lineHeight": "14px", "letterSpacing": "0.1em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
